baseURL = "http://alejio.github.io"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Alex Spanos"

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode = "en"
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName = "English"

# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = "G-ZQB3XPKYKM"

# copyright description used only for seo schema
copyright = ""

# Author config
[author]
  name = "Alex Spanos"
  email = ""
  link = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
  [[menu.main]]
    weight = 2
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "light"
  # public git repo url only then enableGitInfo is true
  # LoveIt NEW | 0.2.0 date format
  dateFormat = "02-01-2006"
  # website title for Open Graph and Twitter Cards
  title = ""
  # website description for RSS, SEO, Open Graph and Twitter Cards
  description = "An assortment of opinions, reflections and semi-relevant tangents of a Data Scientist navigating the uncertain waters of startup life."
  # website images for Open Graph and Twitter Cards
  # images = ["/logo.png"]

  # Header config
  [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    # [params.header.title]
    #   # URL of the LOGO
    #   logo = ""
    [params.header.title]
    logo = ""
      # title name
      name = "Alex Spanos"
      #   # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      #   # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      #   # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

  # Footer config
  [params.footer]
    enable = false
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2023
    # ICP info only in China (HTML format is supported)
    # icp = ""
    # license info (HTML format is supported)
    # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # LoveIt NEW | 0.2.0 Section (all posts) page config
  [params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # LoveIt NEW | 0.2.0 List (category or tag) page config
  [params.list]
    # special amount of posts in each list page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/images/alex.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = ""
      # subtitle shown in home page (HTML format is supported)
      subtitle = "An assortment of opinions, reflections and semi-relevant tangents of a Data Scientist navigating the uncertain waters of startup life."
      # whether to use typeit animation for subtitle
      typeit = false
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      # disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 1
      # LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      # default behavior when you don't set "hiddenFromHomePage" in front matter
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "alejio"
    Linkedin = "alexspanos"
    Twitter = "alexiospanos"  
    RSS = true # LoveIt NEW | 0.2.0

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

  # LoveIt NEW | 0.2.0 Analytics config
  [params.analytics]
    enable = false
